### ISSUE TITLE
SetPhotoViewerAssociation doesn't work

### ISSUE THREAD

**Issue by kophe** [owre/Win10-Initial-Setup-Script#1]
Howdy! Thanks for keeping this project alive and updated.

The SetPhotoViewerAssociation feature isn't working how it is supposed to. After running the script, bmp, gif, jpg, png and tif files are still associated to Paint as the default app. Any possible solutions or workarounds for this issue?

I tried both 19041 and 19042 builds.

**Comment by owre** [comment]
Howdy, 

Unfortunately not, it's a bit tricky to set the default program with PowerShell. Microsoft introduced a hash that they use to verify that the default app association has not been tampered with. There is one guy who claims to have figured it out [here](http://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/) but I have not tried it myself.

**Comment by kophe** [comment]
It didn't work for me, but it requires an external .exe, anyway. I don't think it would be the best solution for the script.

Tried the same with [dism](https://docs.microsoft.com/en-us/answers/questions/34423/how-to-auto-run-for-change-default-app-photoviewer.html), without any success either.

Well, I'll keep looking for a workaround and will gladly share if I find anything.

Thanks again!
